### PR TITLE
Add taginfo.json

### PR DESCRIPTION
**Pull request by JesseWeinstein**
Add a taginfo file hand-identified from the code; still needs descriptions, and probably some more tags added, but it's a start!

### CODE REVIEW

**Comment by matkoniecz** [comment]
> hand-identified from the code

So it will require manual maintenance, right?

**Comment by StrandedKitty** [comment]
@JesseWeinstein Thank you for making this list of tags!
@matkoniecz Yes, tags and their desciptions need to be updated manually.

**Comment by JesseWeinstein** [comment]
It doesn't look like this has been deployed to https://streets.gl/taginfo.json yet?

**Comment by hb0nd** [comment]
> It doesn't look like this has been deployed to https://streets.gl/taginfo.json yet?

it's easier to just link directly to it on github :) the PR for including it on Taginfo hasn't been merged yet: https://github.com/taginfo/taginfo-projects/pull/155

**Pull request merged**
